export default () => ({
  app: {
    nodeEnv: process.env.NODE_ENV ?? 'development',
    port: parseInt(process.env.PORT ?? '3000', 10),
    globalPrefix: process.env.GLOBAL_PREFIX ?? 'api',
    corsOrigins: (process.env.CORS_ORIGINS ?? 'http://localhost:3000')
      .split(',')
      .map((origin) => origin.trim())
      .filter(Boolean),
    trustProxy: process.env.TRUST_PROXY === 'true',
    snapshotEnabled: process.env.ENABLE_SNAPSHOT === 'true',
  },
  security: {
    throttleTtlMs: parseInt(process.env.THROTTLE_TTL_MS ?? '60000', 10),
    throttleLimit: parseInt(process.env.THROTTLE_LIMIT ?? '100', 10),
    apiToken: process.env.API_TOKEN ?? 'dev-local-api-token-change-me',
  },
  observability: {
    otelEnabled: process.env.OTEL_ENABLED === 'true',
    otelExporterEndpoint: process.env.OTEL_EXPORTER_OTLP_ENDPOINT,
    logLevel: process.env.LOG_LEVEL ?? 'info',
    metricsToken: process.env.METRICS_TOKEN || undefined,
  },
  cache: {
    defaultTtlSec: parseInt(process.env.CACHE_DEFAULT_TTL_SEC ?? '60', 10),
    maxItems: parseInt(process.env.CACHE_MAX_ITEMS ?? '10000', 10),
  },
  mail: {
    enabled: process.env.MAIL_ENABLED === 'true',
    host: process.env.MAIL_HOST ?? 'localhost',
    port: parseInt(process.env.MAIL_PORT ?? '587', 10),
    secure: process.env.MAIL_SECURE === 'true',
    user: process.env.MAIL_USER ?? '',
    password: process.env.MAIL_PASSWORD ?? '',
    defaultFrom: process.env.MAIL_DEFAULT_FROM ?? '',
    verifyOnStartup: process.env.MAIL_VERIFY_ON_STARTUP === 'true',
    pool: process.env.MAIL_POOL !== 'false',
    maxConnections: parseInt(process.env.MAIL_MAX_CONNECTIONS ?? '5', 10),
    maxMessages: parseInt(process.env.MAIL_MAX_MESSAGES ?? '100', 10),
    connectionTimeoutMs: parseInt(process.env.MAIL_CONNECTION_TIMEOUT_MS ?? '10000', 10),
    greetingTimeoutMs: parseInt(process.env.MAIL_GREETING_TIMEOUT_MS ?? '10000', 10),
    socketTimeoutMs: parseInt(process.env.MAIL_SOCKET_TIMEOUT_MS ?? '15000', 10),
    requireTls: process.env.MAIL_REQUIRE_TLS !== 'false',
    rejectUnauthorized: process.env.MAIL_REJECT_UNAUTHORIZED !== 'false',
    queueEnabled: process.env.MAIL_QUEUE_ENABLED !== 'false',
    queuePollIntervalMs: parseInt(process.env.MAIL_QUEUE_POLL_INTERVAL_MS ?? '1000', 10),
    queueBatchSize: parseInt(process.env.MAIL_QUEUE_BATCH_SIZE ?? '20', 10),
    queueConcurrency: parseInt(process.env.MAIL_QUEUE_CONCURRENCY ?? '5', 10),
    maxAttempts: parseInt(process.env.MAIL_MAX_ATTEMPTS ?? '3', 10),
    retryBaseDelayMs: parseInt(process.env.MAIL_RETRY_BASE_DELAY_MS ?? '10000', 10),
    idempotencyTtlSec: parseInt(process.env.MAIL_IDEMPOTENCY_TTL_SEC ?? '3600', 10),
    templateCacheTtlSec: parseInt(process.env.MAIL_TEMPLATE_CACHE_TTL_SEC ?? '300', 10),
    webhookSecret: process.env.MAIL_WEBHOOK_SECRET || undefined,
  },
  database: {
    host: process.env.DB_HOST ?? 'localhost',
    port: parseInt(process.env.DB_PORT ?? '5432', 10),
    username: process.env.DB_USERNAME ?? '',
    password: process.env.DB_PASSWORD ?? '',
    name: process.env.DB_NAME ?? 'postgres',
    ssl: process.env.DB_SSL === 'true',
    sslRejectUnauthorized: process.env.DB_SSL_REJECT_UNAUTHORIZED !== 'false',
    sslCa: process.env.DB_SSL_CA,
    retryAttempts: parseInt(process.env.DB_RETRY_ATTEMPTS ?? '5', 10),
    retryDelayMs: parseInt(process.env.DB_RETRY_DELAY_MS ?? '3000', 10),
  },
});
